var json_Found_at_Telecommunication_Leningrad_1959copy_2 = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": null, "author": "Варден, Бартел Лендерт ван дер. ", "title": "    Пробуждающаяся наука [Текст] = Ontwakende Wetenschap : математика Древнего Египта, Вавилона и Греции : пер. с гол. \/ Б. Л. Варден ; пер. И. Н. Веселовский. - М. : Физматгиз, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": -47.383330, "author_y": -171.466667, "affiliation": null }, "geometry": { "type": "Point", "coordinates": [ -171.466667, -47.38333 ] } },
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": null, "author": "Верн, Жюль. ", "title": "    Плавучий остров [Текст] : роман : пер. с фр. \/ Ж. Верн ; пер.: Е. Лопырева, Н. Рыкова ; худож. П. И. Луганский. - Петрозаводск : Гос. изд-во Карел. АССР, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": 48.856700, "author_y": 2.350800, "affiliation": null }, "geometry": { "type": "Point", "coordinates": [ 2.3508, 48.8567 ] } },
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": null, "author": "Гарди, Томас. ", "title": "    Повести и рассказы [Текст] : пер. с англ. \/ Т. Гарди ; пер., ред., сост. О. Холмская, авт. предисл. И. Канторович. - Москва : Государственное издательство художественной литературы, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": null, "author_y": null, "affiliation": null }, "geometry": { "type": "Point", "coordinates": [ 0.0, 0.0 ] } },
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": null, "author": "Эффель, Жан. ", "title": "    Сотворение мира и человека [Текст] : биография отдельного лица \/ Ж. Эффель. - М. : Политиздат, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": 48.856700, "author_y": 2.350800, "affiliation": null }, "geometry": { "type": "Point", "coordinates": [ 2.3508, 48.8567 ] } },
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": 16.000000, "author": "Эшби, У. Росс ", "title": "    Введение в кибернетику [Текст] : монография : пер. с англ. \/ У. Росс Эшби ; пер. Д. Г. Лахути ; ред. В. А. Успенский ; авт. предисл. А. Н. Колмогоров. - М. : Иноиздат, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": 51.870000, "author_y": -2.240000, "affiliation": null }, "geometry": { "type": "Point", "coordinates": [ -2.24, 51.87 ] } },
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": null, "author": "Ожешко, Элиза", "title": "    Аргонавты [Текст] : роман : пер. с пол. \/ Э. Ожешко ; пер. Е. М. Рифтина ; авт. предисл. А. Дейч. - М. : Гослитиздат, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": 53.666667, "author_y": 23.833333, "affiliation": null }, "geometry": { "type": "Point", "coordinates": [ 23.833333, 53.666667 ] } },
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": null, "author": "Попов, Е. П. ", "title": "    Автоматическое регулирование [Текст] : основные понятия \/ Е. П. Попов. - 3-е изд., стер. - М. : Физматгиз, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": 50.450000, "author_y": 30.523333, "affiliation": "начальник кафедры автоматизации в Баумана" }, "geometry": { "type": "Point", "coordinates": [ 30.523333, 50.45 ] } },
{ "type": "Feature", "properties": { "source_x": 59.937500, "source_y": 30.308611, "index": null, "author": "Джакония, В. Е. ", "title": "    Стереотелевидение [Текст] : учебное пособие. Вып. 4 \/ В. Е. Джакония, П. В. Шмаков ; ред. П. В. Шмаков ; Министерство связи СССР, ЛЭИС им. проф. М. А. Бонч-Бруевича, Кафедра телевидения. - Л. : ЛЭИС, 1959.", "publishing_house": null, "page_count": null, "tag1": null, "tag2": null, "tag3": null, "publish_x": null, "publish_y": null, "publish_x2": null, "publish_y2": null, "author_x": null, "author_y": null, "affiliation": null }, "geometry": { "type": "Point", "coordinates": [ 0.0, 0.0 ] } }
]
}
